### ISSUE TITLE
bug in operation

### ISSUE THREAD

**Issue by billy-mosse** [ajcr/transfinite#2]
3*(w*2+4) = w*6+16 by the distributive law for ordinals, but output is \omega\cdot2 + 4

**Comment by ajcr** [comment]
Thanks for raising the issue. It looks like there is a bug here: 3*(w*2+4) should actually be w*2 + 12.

It looks like the finite ordinals are not multiplied correctly here so I'll try and fix this.

**Comment by billy-mosse** [comment]
hahahahah, sorry. I had a brain fart. Yes, you have a bug but 3*4=12, not 16, and you are right, 3*w*2 = w*2, not w*6

**Comment by ajcr** [comment]
Fixed by new implementation.

Sorry for the delay!
